### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by 459699** [Emory-Melody/EpiLearn#1]
installed epilearn, but when runing the example ,the error happend:ModuleNotFoundError: No module named 'torch'

**Comment by myweiii** [comment]
Hi there! To solve this issue, you may also need to run the command `pip install torch`.

**Comment by myweiii** [comment]
> installed epilearn, but when runing the example ,the error happend:ModuleNotFoundError: No module named 'torch'

Hi there! To solve this issue, you may also need to run the command `pip install torch`.
